### ISSUE TITLE
Setup gh-action to host chart in gh-pages

### ISSUE THREAD

**Issue by lplit** [windmill-labs/windmill-helm-charts#1]
Turn this repo into a chart repository using gh-pages and actions provided by helm.

Official doc: https://helm.sh/docs/topics/chart_repository/#github-pages-example
Reference repo: https://github.com/technosophos/tscharts
Chart release action: https://helm.sh/docs/howto/chart_releaser_action/

**Comment by martysohio** [comment]
The chart is now releasing through action, as long as the version is updated in the Chart.yaml file.
