### ISSUE TITLE
External database missing role setup

### ISSUE THREAD

**Issue by edlouth** [windmill-labs/windmill-helm-charts#27]
When bringing my own database, by setting `databaseUrl`, I encounter a couple of issues.

1. I need to manually create `windmill_user` and `windmill_admin` roles, otherwise some of the pods error.
2. After logging in as the default user I get `Not found: App not found at name g/all/setup_app`, which means I don't substitute the default user for my own etc.

**Comment by rubenfiszel** [comment]
I suspect you were not a superuser in that db ?

Did you see that section: https://docs.windmill.dev/docs/advanced/self_host#run-windmill-without-using-a-postgres-superuser

**Comment by edlouth** [comment]
That looks exactly like the section I need, apologies I didn't find it from the helm docs.

**Comment by rubenfiszel** [comment]
I added it to the README, thanks!
