### ISSUE TITLE
Unable to pass http_proxy environment variables to windmill scripts

### ISSUE THREAD

**Issue by robasp** [windmill-labs/windmill-helm-charts#28]
Hi all

I'm not sure if this is a problem that only occurs with the windmill helm-chart, but I am unable to configure windmill to use a HTTP-Proxy.
I already tried to pass the variables http_proxy and https_proxy as extraArgs to all the windmill deployments in the helm values and I was able to "kubectl exec" into the containers and access the internet using the configured http-Proxy.

However, when i try to run a python script in Windmill, the proxy does not seem to work. I cannot import any python modules from the internet.

![image](https://github.com/windmill-labs/windmill-helm-charts/assets/105059474/f813bad1-1eb4-496c-952b-d31f6bde76bd)

When I run "print(os.environ)", my envs (http_proxy & https_proxy) do not show up.

Is this behaviour expected and is it somehow possible to pass global envs to windmill scripts?

Thanks and kind regards
Robin

**Comment by rubenfiszel** [comment]
Hi @robasp,

I'm on it. I think it should be sufficient to pass http_proxy and https_proxy as env variable to the forked processes running the script. I'm doing a fix to this effect right now. Would you have time to check later today?

**Comment by rubenfiszel** [comment]
Released windmill 1.111.2 with beta support for http_proxy and bumped helm charts with 1.6.5 with that. Let me know how it goes.

**Comment by robasp** [comment]
Hi @rubenfiszel 
Thanks for your quick response. I updated to 1.6.5./1.111.2.
Unfortunately this did not solve the problem. I'm still cannot import any Python modules other than "os" and I still don't see any API suggestions.
print(os.environ) does however return HTTP_PROXY and HTTPS_PROXY now:
![image](https://github.com/windmill-labs/windmill-helm-charts/assets/105059474/96352eca-409b-4dc4-acad-430c653e7213)

Let me know if i can provide more information.

Also, could you addthe env "no_proxy" as well? This would allow one to configure exceptions (e.g. for local URLs)

**Comment by rubenfiszel** [comment]
Added NO_PROXY + a fix attempt for pip install proxy, in 1.6.6

**Comment by rubenfiszel** [comment]
Can you confirm that it's enough to set http_proxy and https_proxy to do a pip install in your environement ? Can you ssh  into the worker or any container and attempt a pip install ?

**Comment by robasp** [comment]
sure:
I ran the following commands from the container shell:
`env | grep -i http`
`pip install cowsay`

Without proxy environment variables:
![image](https://github.com/windmill-labs/windmill-helm-charts/assets/105059474/365050c0-d7f9-4699-8d20-e4ab26c2dc61)

This is the same error I get when I try to run a Python Script in the Windmill UI.

With proxy environment variables:
![image](https://github.com/windmill-labs/windmill-helm-charts/assets/105059474/9a783505-773a-4ea4-b0cf-839b939fb5b6)
This works prefectly.

Also, HTTP_PROXY and http_proxy both work. So theres no difference when using uppercase envs.

**Comment by rubenfiszel** [comment]
Thanks for the report, I just released an update with 1.112.0 that should fix this. Thank you for your patience!

**Comment by robasp** [comment]
Thanks a lot for your work, imports works perfectly in Python scripts on worker containers now.

The one remaining problem is that i cannot connect to APIs or other resources. Could this be related to the proxy problem? e.g. one of the other containers not respecting proxy envs?
![image](https://github.com/windmill-labs/windmill-helm-charts/assets/105059474/f5c460ed-a6e6-4af8-b691-c9df631c38c8)

**Comment by rubenfiszel** [comment]
It's more likely you either skipped the setup step, or the setup step could not sync because of the http_proxy

Go to the admins workspace (available if superadmins), and run the sync resource types script.

**Comment by robasp** [comment]
Thanks, i ran the sync resource types script. At first there was a problem accessing the INTERNAL_BASE_URL (http://windmill-app:8000).
I had to add "windmill-app" and the other internal hostnames to the no_proxy environment variable so internal connections don't try to connect via http_proxy.

**Comment by rubenfiszel** [comment]
Update on this, we changed the way BASE_INTERNAL_URL work to hit localhost only, so one would have to set NO_PROXY=localhost.

However, we will add it by default very soon so it won't be necessary
