### ISSUE TITLE
Configure postgres credentials to be secret

### ISSUE THREAD

**Issue by martysohio** [windmill-labs/windmill-helm-charts#3]
For demo purposes, postgres creds are currently plaintext. Very bad, will change to use secrets.

**Comment by drewburr** [comment]
A secret would be preferred so we can properly manage this credential information. Requiring this password in Values.yaml makes it impossible to store this configuration in source control

**Comment by rubenfiszel** [comment]
I currently fixed this under the form of https://github.com/windmill-labs/windmill-helm-charts/commit/0c4afa29e4c22660797ce4f7db8c3221d95aaa16
which adds a databaseUrlSecretName.

We could also go the route of: https://github.com/windmill-labs/windmill-helm-charts/pull/23
