### ISSUE TITLE
Error: UPGRADE FAILED: parse error at (windmill/templates/dedicated-workers.yaml:132): unexpected EOF

### ISSUE THREAD

**Issue by GrbrELO** [windmill-labs/windmill-helm-charts#36]
Bonjour. When performing a `helm upgrade mywindmill windmill/windmill -n windmill` after I executed `helm repo update windmill` I got the following error message. "Error: UPGRADE FAILED: parse error at (windmill/templates/dedicated-workers.yaml:132): unexpected EOF"

**Comment by evtimokn** [comment]
Hi, can you add one more {{- end }}, then it should be fine.
