### ISSUE TITLE
Init Script in not available in  the Worker Management UI

### ISSUE THREAD

**Issue by cyrilbkr** [windmill-labs/windmill-helm-charts#44]
Hi, 

The Init Script box parameter seem not available in the Worker Management UI when using this Helm chart. 
I m using the Helm chart with Windmill CE v1.181.0 docker image. 

<img width="798" alt="Capture d’écran 2023-10-10 à 08 11 09" src="https://github.com/windmill-labs/windmill-helm-charts/assets/31832102/8370b848-6cb7-4b24-8928-e7bc7f3b2413">

If I use the same image with the Docker-compose file provided in the doc, the Init Script box is available, and the Worker Management UI looks different. 

<img width="798" alt="Capture d’écran 2023-10-10 à 08 16 27" src="https://github.com/windmill-labs/windmill-helm-charts/assets/31832102/b8a448a8-e666-4d05-a7e0-a2f8aa450f88">

Am i missing something ? 

Thanks !

**Comment by rubenfiszel** [comment]
It's available in latest but it's unreleased yet: https://github.com/windmill-labs/windmill/pull/2393

However, it will only work on EE and you seem to be CE

**Comment by cyrilbkr** [comment]
So the only solution for having extra tools/binary setup in the workers are using a custom Docker image right ?

**Comment by rubenfiszel** [comment]
Yes but we will offer cheaper hobbyists license for EE features soon so that would be an option too.

**Comment by cyrilbkr** [comment]
allright, thanks @rubenfiszel !
