### ISSUE TITLE
Typo in template file cause error in deploy

### ISSUE THREAD

**Issue by Yoshino-s** [windmill-labs/windmill-helm-charts#46]
Here at: https://github.com/windmill-labs/windmill-helm-charts/blob/8bc914225c8352f69614458f55731e8e2636b48d/charts/windmill/templates/worker-groups.yaml#L113

Which missing `$` at `"{{ .Values.enterprise.s3CacheBucket }}"`

**Comment by rubenfiszel** [comment]
fixed, thanks!
