### ISSUE TITLE
BYPASSRLS not allowed on Azure flexible Postgres db

### ISSUE THREAD

**Issue by denispol** [windmill-labs/windmill-helm-charts#57]
Hi, regarding the use of a managed Postgres database in Azure, superuser access is not given to the owner. Therefore, there's no way to give BYPASSRLS permissions. The init-db SQL file may need to be adjusted to match scenarios where superuser is not given in cloud-hosted managed databases.

**Issue for windmill main repo, please close**

**Comment by rubenfiszel** [comment]
For posterity: 
![image](https://github.com/windmill-labs/windmill-helm-charts/assets/275584/9f56ea43-69bb-4edb-961f-92f32a202c7f)
