### ISSUE TITLE
SecurityContext capability is incomplete

### ISSUE THREAD

**Issue by avo-sepp** [windmill-labs/windmill-helm-charts#73]
Each app supports a SecurityContext in the values file. However, this only renders the SecurityContext at the pod level. Many of the capabilities required need to also modify values in the container level. 

capabilities, allowPrivilegeEscalation are not available at the Pod level. 

This is usually solved in a Helm chart by having two locations in the values file where a securityContext is filled. 
`containerSecurityContext` and `podSecurityContext` 

My vote, for best backwards compatibility, is to keep `securityContext` and add `containerSecurityContext` which renders into the container block of each deployment.

**Comment by rubenfiszel** [comment]
Thank you for pointing it out. The proposal sounds good. Would you be up to make it a PR contribution?

**Comment by avo-sepp** [comment]
I'm not sure if my original plan works, after looking deeper I can see it's harder to fix because the securityContext isn't consistent between applications. 

For example, the Windmill App and lsp configure SecurityContext at the Pod level. However, the windmill-worker configures it at the container level. But both use the same name. If I were to modify this behavior to make the naming consistent, I would break backwards compatibility in some sense. I would be changing the behavior of the securityContext values in some deployments. 

So some decision on how to handle this has to be made on your end.

**Comment by rubenfiszel** [comment]
Thank you for pointing it out.

The best in this case is likely to introduce:
`containerSecurityContext:` and `podSecurityContext` and deprecate `securityContext:` but keep it backward compatible to avoid breaks. I would understand you wouldn't want to do such change, we will do in the next few days if you prefer not to.

**Comment by avo-sepp** [comment]
I'm sorry, I don't have the resources presently to help you make that change.

**Comment by rubenfiszel** [comment]
@avo-sepp fixed in latest helm release. Added podSecurityContext and containerSecurityContext in every services while keeping back-compatibility with legacy securityContext

**Comment by avo-sepp** [comment]
I'll have a look now!

**Comment by avo-sepp** [comment]
Sorry, this fix is incomplete. For example, in the Windmill App template there is no mapping of the containerSecurityContext to the securityContext in the container. There is only the pod level security context. I didn't check the others, I just know the app one doesn't have it.

**Comment by rubenfiszel** [comment]
You're right, on it

**Comment by rubenfiszel** [comment]
@avo-sepp fixed on very latest release, thanks for finding the issue

**Comment by avo-sepp** [comment]
Looks like the `app` and `lsp` are working now! Thank you. I think this can be closed and if I run into anything else with this I'll let you know. Thank you again!!
